// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { AppPackageDescriptor } from '@citadel/platform/app';

export const bundledAppDescriptorByPackageName: Record<string, AppPackageDescriptor> = {
  "@citadel/app-chat": {
    appId: "chat",
    manifest: {
      appId: "chat",
      label: "Chat",
      defaultSpaceId: "general",
      persistence: "sqlite",
      version: "0.1.0"
    },
    packageName: "@citadel/app-chat",
    client: {
      subpath: "./client",
      registrationExport: "chatClientRegistration"
    },
    server: {
      subpath: "./server",
      registrationExport: "chatServerRegistration"
    }
  },
  "@citadel/app-chess": {
    appId: "chess",
    manifest: {
      appId: "chess",
      label: "Chess",
      defaultSpaceId: "general",
      persistence: "sqlite",
      version: "0.1.0"
    },
    packageName: "@citadel/app-chess",
    client: {
      subpath: "./client",
      registrationExport: "chessClientRegistration"
    },
    server: {
      subpath: "./server",
      registrationExport: "chessServerRegistration"
    }
  },
  "@citadel/app-snake": {
    appId: "snake",
    manifest: {
      appId: "snake",
      label: "Snake",
      defaultSpaceId: "general",
      persistence: "none",
      version: "0.1.0"
    },
    packageName: "@citadel/app-snake",
    client: {
      subpath: "./client",
      registrationExport: "snakeClientRegistration"
    },
    server: {
      subpath: "./server",
      registrationExport: "snakeServerRegistration"
    }
  }
};
