// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { ServerAppRegistration } from '@citadel/platform/server-app';
import { chatServerRegistration as bundledServerRegistration0 } from '@citadel/app-chat/server';
import { chessServerRegistration as bundledServerRegistration1 } from '@citadel/app-chess/server';
import { snakeServerRegistration as bundledServerRegistration2 } from '@citadel/app-snake/server';

export const bundledServerRegistrationByPackageName: Record<string, ServerAppRegistration<any>> = {
  '@citadel/app-chat': bundledServerRegistration0,
  '@citadel/app-chess': bundledServerRegistration1,
  '@citadel/app-snake': bundledServerRegistration2
};
