// Generated by scripts/generate-bundled-apps.mjs. Do not edit by hand.
import type { ClientAppRegistration } from '@citadel/platform/client';
import { chatClientRegistration as bundledClientRegistration0 } from '@citadel/app-chat/client';
import { chessClientRegistration as bundledClientRegistration1 } from '@citadel/app-chess/client';
import { snakeClientRegistration as bundledClientRegistration2 } from '@citadel/app-snake/client';

export const bundledClientRegistrationByPackageName: Record<string, ClientAppRegistration<any>> = {
  '@citadel/app-chat': bundledClientRegistration0,
  '@citadel/app-chess': bundledClientRegistration1,
  '@citadel/app-snake': bundledClientRegistration2
};
